// src/constants/roles.js
export const ROLES = {
    SUPERADMIN: 'superadmin',
    ADMIN: 'admin',
    STAFF: 'staff',
    EXAMINATOR: 'examinator',
    TEACHER: 'teacher',
    USER: 'user',
    GUEST: 'guest',
    // Add other roles as needed
};

export const ROLES_PERMISSIONS = {
    SUPERADMIN: [
        'create-user',
        'update-user',
        'delete-user',
        'view-user',
        'create-role',
        'update-role',
        'delete-role',
        'view-role',
        'create-permission',
        'update-permission',
        'delete-permission',
        'view-permission',
        'create-exam',
        'update-exam',
        'delete-exam',
        'view-exam',
        'create-question',
        'update-question',
        'delete-question',
        'view-question',
        'create-answer',
        'update-answer',
        'delete-answer',
        'view-answer',
        'create-course',
        'update-course',
        'delete-course',
        'view-course',
        'create-subject',
        'update-subject',
        'delete-subject',
        'view-subject',
        'create-lesson',
        'update-lesson',
        'delete-lesson',
        'view-lesson',
        'create-material',
        'update-material',
        'delete-material',
        'view-material',
        'create-assignment',
        'update-assignment',
    ],
    ADMIN: [
        'create-user',
    ],
    STAFF: [
        'create-exam',
        'update-exam',
        'delete-exam',
        'view-exam',
        'create-question',
        'update-question',
        'delete-question',
        'view-question',
        'create-answer',
        'update-answer',
        'delete-answer',
        'view-answer',
        'create-course',
        'update-course',
        'delete-course',
        'view-course',
        'create-subject',
        'update-subject',
        'delete-subject',
        'view-subject',
        'create-lesson',
        'update-lesson',
        'delete-lesson',
        'view-lesson',
        'create-material',
        'update-material',
        'delete-material',
        'view-material',
        'create-assignment',
        'update-assignment',
        'view-assignment',
        'create-class',
        'update-class',
        'delete-class',
        'view-class',
        'create-classroom',],
    EXAMINATOR: [
        'create-exam',
        'update-exam',
        'delete-exam',

        'view-exam',
        'create-question',
    ],
    TEACHER: [
        'create-exam',],
    USER: [
        'view-exam',
        'view-question',
        'view-answer',
        'view-course',
        'view-subject',
        'view-lesson',
        'view-material',
        'view-assignment',
        'view-class',
        'view-classroom',
        'view-daily-attendance',
        'view-class-routine',

        'view-calendar',
    ]
}
    ;